server:
  port: 9080
eureka:
  server:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: authServer

  datasource:
      url: "jdbc:mysql://192.168.1.178/demouserdb?useUnicode=true&useSSL=false"
      username: demouser
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations:
    classpath:mapping/*.xml
  type-aliases-package:
    com.user.info.entity